name: Build Signed APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      # Step 1: Decode Keystore from base64
      - name: Decode Keystore
        run: |
          echo "${{ secrets.KEYSTORE_BASE64 }}" | base64 -d > android.jks

      # Step 2: Build Release APK using Buildozer
      - name: Build Release APK
        uses: digreatbrian/buildozer-action@v2
        with:
          python-version: 3.11
          buildozer-cmd: buildozer -v android release

      # Step 3: Sign with jarsigner (v1 scheme)
      - name: Sign the APK manually
        run: |
          APK_PATH=$(find ./bin -name "*-release-unsigned.apk" | head -n 1)
          jarsigner -verbose -sigalg SHA256withRSA -digestalg SHA-256 \
            -keystore android.jks \
            -storepass "${{ secrets.KEYSTORE_PASSWORD }}" \
            -keypass "${{ secrets.KEY_PASSWORD }}" \
            "$APK_PATH" "${{ secrets.KEY_ALIAS }}"

      # Step 4: Install zipalign and apksigner
      - name: Install zipalign and apksigner
        run: |
          sudo apt-get update
          sudo apt-get install -y zipalign apksigner

      # Step 5: Zipalign and sign with apksigner (v1 + v2)
      - name: Zipalign and apksigner sign
        run: |
          APK_PATH=$(find ./bin -name "*-release-unsigned.apk" | head -n 1)
          ZIPALIGNED_APK="${APK_PATH/-unsigned/-aligned.apk}"
          FINAL_APK="${APK_PATH/-unsigned/-signed.apk}"

          # Zipalign the APK
          zipalign -v 4 "$APK_PATH" "$ZIPALIGNED_APK"

          # Sign with apksigner (v1 + v2)
          apksigner sign \
            --ks android.jks \
            --ks-key-alias "${{ secrets.KEY_ALIAS }}" \
            --ks-pass pass:"${{ secrets.KEYSTORE_PASSWORD }}" \
            --key-pass pass:"${{ secrets.KEY_PASSWORD }}" \
            --out "$FINAL_APK" \
            "$ZIPALIGNED_APK"

      # Step 6: Upload Signed APK Artifact
      - name: Upload Signed APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: signed-release-apk
          path: ./bin/*-release-signed.apk
